name: solo-dev
description: "ソロ開発用"

focus: solo-dev

windows:
  - name: review
    panes:
      - id: terminal
        name: Terminal
        pane: 1
        command: null
      - id: editor
        name: Editor
        pane: 2
        command: nvim
    layout:
      splits:
        - { source: 1, direction: h, percent: 50 }
      focus: 1

  - name: solo-dev
    panes:
      - id: developer
        name: Developer
        pane: 1
        command: 'yoloclaude --agent solo-dev-developer-agent'
      - id: human
        name: Human
        pane: 2
        command: "cd {{meta.session_dir}} && nvim"
    layout:
      splits:
        - { source: 1, direction: h, percent: 50 }
      focus: 1

states:
  planning:
    description: "人間と対話しながら計画を策定する"
    color: blue
    entry_point: true
  human_plan_review:
    description: "人間に計画をレビューしてもらう"
    color: yellow
  implement:
    description: "計画を元に実装する"
    color: blue
  human_code_review:
    description: "人間にコードレビューしてもらう"
    color: yellow
